src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $nbreConvive = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $dateReservation = null;

    #[ORM\Column]
    private ?\DateTime $heureReservation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $allergies = null;

    #[ORM\Column]
    private ?\DateTime $dateCreation = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?restaurant $restaurant = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbreConvive(): ?int
    {
        return $this->nbreConvive;
    }

    public function setNbreConvive(int $nbreConvive): static
    {
        $this->nbreConvive = $nbreConvive;

        return $this;
    }

    public function getDateReservation(): ?\DateTime
    {
        return $this->dateReservation;
    }

    public function setDateReservation(\DateTime $dateReservation): static
    {
        $this->dateReservation = $dateReservation;

        return $this;
    }

    public function getHeureReservation(): ?\DateTime
    {
        return $this->heureReservation;
    }

    public function setHeureReservation(\DateTime $heureReservation): static
    {
        $this->heureReservation = $heureReservation;

        return $this;
    }

    public function getAllergies(): ?string
    {
        return $this->allergies;
    }

    public function setAllergies(?string $allergies): static
    {
        $this->allergies = $allergies;

        return $this;
    }

    public function getDateCreation(): ?\DateTime
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTime $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getRestaurant(): ?restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?restaurant $restaurant): static
    {
        $this->restaurant = $restaurant;

        return $this;
    }
}

src/Controller/GalerieController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use App\Repository\PhotoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class GalerieController extends AbstractController
{
    #[Route('/galerie', name: 'app_galerie')]
    public function index(PhotoRepository $photoRepository): Response
    {
        // Récupérer toutes les photos depuis la base de données
        $photos = $photoRepository->findAll();

        return $this->render('galerie/index.html.twig', [
            'photos' => $photos,
        ]);
    }
}

templates/galerie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Galerie{% endblock %}

{% block body %}
<div class="hero-scene text-center text-white">
    <div class="hero-scene-content">
        <h1>Galerie</h1>
    </div>
</div>

<div class="container">
    {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
    <div class="text-center">
        <a href="{{ path('app_photo_new') }}" class="btn btn-primary mb-3">Ajouter une photo</a>
    </div>
    {% endif %}

    <div class="row row-cols-2 row-cols-lg-3" id="allImages">
    {% for photo in photos %}
        <div class="col p-3">
            <div class="image-card text-white">
                <img src={{ photo.chemin }} class="rounded w-100" alt="{{ photo.titre }}">
                <p class="titre-image">{{ photo.titre }}</p>
                {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
                <div class="action-image-buttons">
                    <a href="{{ path('app_photo_edit', {'id': photo.id}) }}" class="btn btn-outline-light">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    {% include 'photo/_delete_form.html.twig' with { 'photo': photo } %}
                </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
    <div class="text-center mb-3">
        <a href="#" class="btn btn-primary">Réserver</a>
    </div>
</div>
  
{% endblock %}